[toolchain]
package_manager = "Yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
armeni_staking = "6VYc9ZpdV9DuzJUXTfgnYxoT7hV8rbBphT6PZ7rvrHS4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = '~\.config\solana\id.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
